project:
  type: book

book:
  title: "Encuesta de Inclusión Digital NUDOS 2023"
  subtitle: "Manual de uso metodológico"
  author: "Teresa Correa & Nicolás Tobar"
  date: "Última actualización: `r Sys.Date()`"
  chapters:
    - index.qmd
    - ficha.qmd
    - variables.qmd
  language: es
  sharing: [twitter, facebook, linkedin]
  repo-url: https://github.com/milenio-nudos/2023_digital_inclusion

format:
  html:
    theme: cosmo

execute: 
  echo: false
  warning: false
  error: false
  
editor: visual