project:
  type: book

book:
  title: "Encuesta de Inclusión Digital NUDOS 2023"
  subtitle: "Manual de uso metodológico"
  author: "Teresa Correa & Nicolás Tobar"
  date: "Última actualización: `r Sys.Date()`"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  language: es
  cover-image: images/logo.png
  sharing: [twitter, facebook, linkedin]

format:
  html:
    theme: cosmo

editor: visual

